#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: ../src/Controller/
    type: annotation
    # (the type: annotation option also applies to attributes...)
api_controllers:
    resource: ../src/Controller/Api/
    type: annotation
    prefix: api
